--[[
	BaseballBat.spec.lua
	TestEZ tests for BaseballBat module
]]

return function()
  local ReplicatedStorage = game:GetService("ReplicatedStorage")
  local Shared = ReplicatedStorage:WaitForChild("Shared")
  local BaseballBat = require(Shared:WaitForChild("BaseballBat"))
  local PredatorSpawning = require(Shared:WaitForChild("PredatorSpawning"))

  describe("BaseballBat", function()
    describe("createBatState", function()
      it("should return unequipped bat", function()
        local batState = BaseballBat.createBatState()
        expect(batState).to.be.ok()
        expect(batState.isEquipped).to.equal(false)
      end)
    end)

    describe("equip", function()
      it("should set isEquipped to true", function()
        local batState = BaseballBat.createBatState()
        local result = BaseballBat.equip(batState)
        expect(result).to.equal(true)
        expect(batState.isEquipped).to.equal(true)
      end)

      it("should fail when already equipped", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        local result = BaseballBat.equip(batState)
        expect(result).to.equal(false)
      end)
    end)

    describe("unequip", function()
      it("should set isEquipped to false", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        local result = BaseballBat.unequip(batState)
        expect(result).to.equal(true)
        expect(batState.isEquipped).to.equal(false)
      end)

      it("should fail when already unequipped", function()
        local batState = BaseballBat.createBatState()
        local result = BaseballBat.unequip(batState)
        expect(result).to.equal(false)
      end)
    end)

    describe("toggle", function()
      it("should switch equip state", function()
        local batState = BaseballBat.createBatState()
        local result1 = BaseballBat.toggle(batState)
        expect(result1).to.equal(true)
        local result2 = BaseballBat.toggle(batState)
        expect(result2).to.equal(false)
      end)
    end)

    describe("canSwing", function()
      it("should return false when not equipped", function()
        local batState = BaseballBat.createBatState()
        local canSwing = BaseballBat.canSwing(batState, 0)
        expect(canSwing).to.equal(false)
      end)

      it("should return true when equipped and off cooldown", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        local canSwing = BaseballBat.canSwing(batState, 0)
        expect(canSwing).to.equal(true)
      end)
    end)

    describe("swing cooldown", function()
      it("should prevent immediate second swing", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        BaseballBat.performSwing(batState, 0)
        local canSwing = BaseballBat.canSwing(batState, 0.1)
        expect(canSwing).to.equal(false)
      end)

      it("should expire after configured time", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        BaseballBat.performSwing(batState, 0)
        local config = BaseballBat.getConfig()
        local canSwing = BaseballBat.canSwing(batState, config.swingCooldownSeconds + 0.1)
        expect(canSwing).to.equal(true)
      end)
    end)

    describe("getSwingCooldownRemaining", function()
      it("should return correct value", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        BaseballBat.performSwing(batState, 0)
        local config = BaseballBat.getConfig()
        local remaining = BaseballBat.getSwingCooldownRemaining(batState, 0.2)
        local expected = config.swingCooldownSeconds - 0.2
        expect(math.abs(remaining - expected) < 0.01).to.equal(true)
      end)
    end)

    describe("performSwing", function()
      it("should increment swing count", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        BaseballBat.performSwing(batState, 0)
        local config = BaseballBat.getConfig()
        BaseballBat.performSwing(batState, config.swingCooldownSeconds + 0.1)
        expect(batState.swingsCount).to.equal(2)
      end)
    end)

    describe("hitPlayer", function()
      it("should return knockback result", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        local result = BaseballBat.hitPlayer(batState, "player123", 0)
        expect(result.success).to.equal(true)
        expect(result.hitType).to.equal("player")
        expect(result.knockback).to.equal(true)
      end)
    end)

    describe("swingMiss", function()
      it("should return miss result", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        local result = BaseballBat.swingMiss(batState, 0)
        expect(result.success).to.equal(true)
        expect(result.hitType).to.equal("miss")
      end)
    end)

    describe("isInRange", function()
      it("should return true for close distances", function()
        local config = BaseballBat.getConfig()
        local inRange = BaseballBat.isInRange(config.swingRangeStuds - 1)
        expect(inRange).to.equal(true)
      end)

      it("should return false for far distances", function()
        local config = BaseballBat.getConfig()
        local inRange = BaseballBat.isInRange(config.swingRangeStuds + 1)
        expect(inRange).to.equal(false)
      end)
    end)

    describe("getKnockbackParams", function()
      it("should return valid values", function()
        local params = BaseballBat.getKnockbackParams()
        expect(params.force > 0).to.equal(true)
        expect(params.duration > 0).to.equal(true)
      end)
    end)

    describe("getConfig", function()
      it("should return valid configuration", function()
        local config = BaseballBat.getConfig()
        expect(config.swingCooldownSeconds > 0).to.equal(true)
        expect(config.swingRangeStuds > 0).to.equal(true)
        expect(config.predatorDamage > 0).to.equal(true)
        expect(config.playerKnockbackForce > 0).to.equal(true)
      end)
    end)

    describe("reset", function()
      it("should clear bat state", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        BaseballBat.performSwing(batState, 0)
        BaseballBat.reset(batState)
        expect(batState.isEquipped).to.equal(false)
        expect(batState.swingsCount).to.equal(0)
        expect(batState.lastSwingTime).to.equal(0)
      end)
    end)

    describe("getStats", function()
      it("should return correct statistics", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        BaseballBat.performSwing(batState, 5)
        local stats = BaseballBat.getStats(batState)
        expect(stats.isEquipped).to.equal(true)
        expect(stats.totalSwings).to.equal(1)
        expect(stats.lastSwingTime).to.equal(5)
      end)
    end)

    describe("getDisplayInfo", function()
      it("should show cooldown correctly", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        BaseballBat.performSwing(batState, 0)
        local displayInfo = BaseballBat.getDisplayInfo(batState, 0.2)
        expect(displayInfo.isEquipped).to.equal(true)
        expect(displayInfo.canSwing).to.equal(false)
        expect(displayInfo.cooldownRemaining > 0).to.equal(true)
      end)
    end)

    describe("getHitsToDefeat", function()
      it("should return bat hits from PredatorConfig", function()
        local hits = BaseballBat.getHitsToDefeat("Rat")
        expect(hits > 0).to.equal(true)
      end)
    end)

    describe("hitPredator", function()
      it("should damage predator on hit", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        local spawnState = PredatorSpawning.createSpawnState()
        local spawnResult = PredatorSpawning.spawnPredator(spawnState, "Rat", "player1", 0)
        expect(spawnResult.success).to.equal(true)
        expect(spawnResult.predator).to.be.ok()

        local predatorId = spawnResult.predator.id
        local result = BaseballBat.hitPredator(batState, spawnState, predatorId, 0)
        expect(result.success).to.equal(true)
        expect(result.hitType).to.equal("predator")
        expect(result.damage > 0).to.equal(true)
      end)

      it("should fail on inactive predator", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        local spawnState = PredatorSpawning.createSpawnState()
        local result = BaseballBat.hitPredator(batState, spawnState, "fake_id", 0)
        expect(result.success).to.equal(false)
      end)

      it("should respect swing cooldown", function()
        local batState = BaseballBat.createBatState()
        BaseballBat.equip(batState)
        local spawnState = PredatorSpawning.createSpawnState()
        local spawnResult = PredatorSpawning.spawnPredator(spawnState, "Rat", "player1", 0)
        expect(spawnResult.success).to.equal(true)
        expect(spawnResult.predator).to.be.ok()

        local predatorId = spawnResult.predator.id
        -- First hit
        BaseballBat.hitPredator(batState, spawnState, predatorId, 0)
        -- Try immediate second hit
        local result = BaseballBat.hitPredator(batState, spawnState, predatorId, 0.1)
        expect(result.success).to.equal(false)
      end)
    end)
  end)
end
