--[[
	ChickenHealth.spec.lua
	TestEZ tests for ChickenHealth module
]]

return function()
  local ReplicatedStorage = game:GetService("ReplicatedStorage")
  local Shared = ReplicatedStorage:WaitForChild("Shared")
  local ChickenHealth = require(Shared:WaitForChild("ChickenHealth"))
  local ChickenConfig = require(Shared:WaitForChild("ChickenConfig"))

  describe("ChickenHealth", function()
    describe("createRegistry", function()
      it("should return valid registry", function()
        local registry = ChickenHealth.createRegistry()
        expect(registry).to.be.ok()
        expect(registry.chickens).to.be.ok()
      end)
    end)

    describe("register", function()
      it("should add chicken to registry", function()
        local registry = ChickenHealth.createRegistry()
        local state = ChickenHealth.register(registry, "chicken1", "BasicChick")
        expect(state).to.be.ok()
        expect(state.chickenId).to.equal("chicken1")
        expect(state.currentHealth).to.equal(state.maxHealth)
      end)

      it("should allow retrieving registered chicken", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local state = ChickenHealth.get(registry, "chicken1")
        expect(state).to.be.ok()
        expect(state.chickenId).to.equal("chicken1")
      end)
    end)

    describe("applyDamage", function()
      it("should reduce health correctly", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local result = ChickenHealth.applyDamage(registry, "chicken1", 20, os.time())
        expect(result.success).to.equal(true)
        expect(result.damageDealt > 0).to.equal(true)
        expect(result.died).to.equal(false)
      end)

      it("should update lastDamageTime", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local currentTime = os.time()
        ChickenHealth.applyDamage(registry, "chicken1", 10, currentTime)
        local state = ChickenHealth.get(registry, "chicken1")
        expect(state.lastDamageTime).to.equal(currentTime)
      end)

      it("should fail for non-existent chicken", function()
        local registry = ChickenHealth.createRegistry()
        local result = ChickenHealth.applyDamage(registry, "nonexistent", 10, os.time())
        expect(result.success).to.equal(false)
      end)
    end)

    describe("chicken death", function()
      it("should die when health reaches 0", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local state = ChickenHealth.get(registry, "chicken1")
        expect(state).to.be.ok()
        local result =
          ChickenHealth.applyDamage(registry, "chicken1", state.maxHealth + 10, os.time())
        expect(result.success).to.equal(true)
        expect(result.died).to.equal(true)
        expect(result.newHealth).to.equal(0)
      end)

      it("should not take more damage when dead", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local state = ChickenHealth.get(registry, "chicken1")
        expect(state).to.be.ok()
        ChickenHealth.applyDamage(registry, "chicken1", state.maxHealth + 10, os.time())
        local result = ChickenHealth.applyDamage(registry, "chicken1", 10, os.time())
        expect(result.success).to.equal(false)
      end)

      it("should set isDead state when killed", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local state = ChickenHealth.get(registry, "chicken1")
        expect(state).to.be.ok()
        ChickenHealth.applyDamage(registry, "chicken1", state.maxHealth + 10, os.time())
        expect(state.isDead).to.equal(true)
      end)
    end)

    describe("regeneration", function()
      it("should regenerate health after delay", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local startTime = os.time()
        ChickenHealth.applyDamage(registry, "chicken1", 20, startTime)

        -- Wait past regen delay
        local regenDelay = ChickenConfig.getHealthRegenDelay()
        local laterTime = startTime + regenDelay + 1

        local result = ChickenHealth.regenerate(registry, "chicken1", 1, laterTime)
        expect(result.success).to.equal(true)
        expect(result.amountHealed > 0).to.equal(true)
      end)

      it("should not regenerate during regen delay", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local startTime = os.time()
        ChickenHealth.applyDamage(registry, "chicken1", 20, startTime)

        -- Try to regen immediately (within delay)
        local result = ChickenHealth.regenerate(registry, "chicken1", 1, startTime + 1)
        expect(result.amountHealed).to.equal(0)
      end)

      it("should not regenerate when at full health", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local regenDelay = ChickenConfig.getHealthRegenDelay()
        local result = ChickenHealth.regenerate(registry, "chicken1", 1, regenDelay + 1)
        expect(result.amountHealed).to.equal(0)
      end)

      it("should not regenerate dead chicken", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local state = ChickenHealth.get(registry, "chicken1")
        expect(state).to.be.ok()
        local startTime = os.time()
        ChickenHealth.applyDamage(registry, "chicken1", state.maxHealth + 10, startTime)
        local regenDelay = ChickenConfig.getHealthRegenDelay()
        local result = ChickenHealth.regenerate(registry, "chicken1", 1, startTime + regenDelay + 1)
        expect(result.success).to.equal(false)
      end)
    end)

    describe("unregister", function()
      it("should remove chicken from registry", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local unregistered = ChickenHealth.unregister(registry, "chicken1")
        local state = ChickenHealth.get(registry, "chicken1")
        expect(unregistered).to.equal(true)
        expect(state).to.equal(nil)
      end)

      it("should return false for non-existent chicken", function()
        local registry = ChickenHealth.createRegistry()
        local unregistered = ChickenHealth.unregister(registry, "nonexistent")
        expect(unregistered).to.equal(false)
      end)
    end)

    describe("rarity health scaling", function()
      it("should give rarer chickens more health", function()
        local commonHealth = ChickenConfig.getMaxHealth("Common")
        local rareHealth = ChickenConfig.getMaxHealth("Rare")
        local legendaryHealth = ChickenConfig.getMaxHealth("Legendary")
        expect(rareHealth > commonHealth).to.equal(true)
        expect(legendaryHealth > rareHealth).to.equal(true)
      end)
    end)

    describe("getHealthPercent", function()
      it("should return correct value", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local state = ChickenHealth.get(registry, "chicken1")
        expect(state).to.be.ok()
        ChickenHealth.applyDamage(registry, "chicken1", state.maxHealth / 2, os.time())
        local percent = ChickenHealth.getHealthPercent(registry, "chicken1")
        expect(percent > 0.4).to.equal(true)
        expect(percent < 0.6).to.equal(true)
      end)

      it("should return 1 for full health", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local percent = ChickenHealth.getHealthPercent(registry, "chicken1")
        expect(percent).to.equal(1)
      end)

      it("should return 0 for dead chicken", function()
        local registry = ChickenHealth.createRegistry()
        ChickenHealth.register(registry, "chicken1", "BasicChick")
        local state = ChickenHealth.get(registry, "chicken1")
        expect(state).to.be.ok()
        ChickenHealth.applyDamage(registry, "chicken1", state.maxHealth + 10, os.time())
        local percent = ChickenHealth.getHealthPercent(registry, "chicken1")
        expect(percent).to.equal(0)
      end)

      it("should return 0 for non-existent chicken", function()
        local registry = ChickenHealth.createRegistry()
        local percent = ChickenHealth.getHealthPercent(registry, "nonexistent")
        expect(percent).to.equal(0)
      end)
    end)

    describe("utility functions", function()
      describe("isFullHealth", function()
        it("should return true for full health", function()
          local registry = ChickenHealth.createRegistry()
          ChickenHealth.register(registry, "chicken1", "BasicChick")
          expect(ChickenHealth.isFullHealth(registry, "chicken1")).to.equal(true)
        end)

        it("should return false after damage", function()
          local registry = ChickenHealth.createRegistry()
          ChickenHealth.register(registry, "chicken1", "BasicChick")
          ChickenHealth.applyDamage(registry, "chicken1", 10, os.time())
          expect(ChickenHealth.isFullHealth(registry, "chicken1")).to.equal(false)
        end)
      end)

      describe("isDamaged", function()
        it("should return false for full health", function()
          local registry = ChickenHealth.createRegistry()
          ChickenHealth.register(registry, "chicken1", "BasicChick")
          expect(ChickenHealth.isDamaged(registry, "chicken1")).to.equal(false)
        end)

        it("should return true after damage", function()
          local registry = ChickenHealth.createRegistry()
          ChickenHealth.register(registry, "chicken1", "BasicChick")
          ChickenHealth.applyDamage(registry, "chicken1", 10, os.time())
          expect(ChickenHealth.isDamaged(registry, "chicken1")).to.equal(true)
        end)
      end)

      describe("getCount", function()
        it("should return correct count", function()
          local registry = ChickenHealth.createRegistry()
          expect(ChickenHealth.getCount(registry)).to.equal(0)
          ChickenHealth.register(registry, "chicken1", "BasicChick")
          expect(ChickenHealth.getCount(registry)).to.equal(1)
          ChickenHealth.register(registry, "chicken2", "BasicChick")
          expect(ChickenHealth.getCount(registry)).to.equal(2)
        end)
      end)

      describe("resetHealth", function()
        it("should restore full health", function()
          local registry = ChickenHealth.createRegistry()
          ChickenHealth.register(registry, "chicken1", "BasicChick")
          ChickenHealth.applyDamage(registry, "chicken1", 20, os.time())
          local result = ChickenHealth.resetHealth(registry, "chicken1")
          expect(result).to.equal(true)
          local state = ChickenHealth.get(registry, "chicken1")
          expect(state.currentHealth).to.equal(state.maxHealth)
        end)

        it("should revive dead chicken", function()
          local registry = ChickenHealth.createRegistry()
          ChickenHealth.register(registry, "chicken1", "BasicChick")
          local state = ChickenHealth.get(registry, "chicken1")
          expect(state).to.be.ok()
          ChickenHealth.applyDamage(registry, "chicken1", state.maxHealth + 10, os.time())
          expect(state.isDead).to.equal(true)
          ChickenHealth.resetHealth(registry, "chicken1")
          expect(state.isDead).to.equal(false)
          expect(state.currentHealth).to.equal(state.maxHealth)
        end)
      end)

      describe("getSummary", function()
        it("should return correct summary", function()
          local registry = ChickenHealth.createRegistry()
          ChickenHealth.register(registry, "chicken1", "BasicChick")
          ChickenHealth.register(registry, "chicken2", "BasicChick")
          ChickenHealth.register(registry, "chicken3", "BasicChick")

          -- Damage one chicken
          ChickenHealth.applyDamage(registry, "chicken2", 10, os.time())

          -- Kill one chicken
          local state3 = ChickenHealth.get(registry, "chicken3")
          expect(state3).to.be.ok()
          ChickenHealth.applyDamage(registry, "chicken3", state3.maxHealth + 10, os.time())

          local summary = ChickenHealth.getSummary(registry)
          expect(summary.total).to.equal(3)
          expect(summary.fullHealth).to.equal(1)
          expect(summary.damaged).to.equal(1)
          expect(summary.dead).to.equal(1)
        end)
      end)
    end)
  end)
end
