--[[
	CombatHealth.spec.lua
	TestEZ tests for CombatHealth module
]]

return function()
  local ReplicatedStorage = game:GetService("ReplicatedStorage")
  local Shared = ReplicatedStorage:WaitForChild("Shared")
  local CombatHealth = require(Shared:WaitForChild("CombatHealth"))
  local PredatorConfig = require(Shared:WaitForChild("PredatorConfig"))

  describe("CombatHealth", function()
    describe("createState", function()
      it("should create valid state with full health", function()
        local state = CombatHealth.createState()
        expect(state).to.be.ok()
        expect(state.health).to.equal(state.maxHealth)
      end)

      it("should create state with default values", function()
        local state = CombatHealth.createState()
        expect(state.isKnockedBack).to.equal(false)
        expect(state.inCombat).to.equal(false)
        expect(state.isIncapacitated).to.equal(false)
        expect(state.lastDamageTime).to.equal(0)
      end)
    end)

    describe("applyDamage", function()
      it("should reduce health", function()
        local state = CombatHealth.createState()
        local initialHealth = state.health
        local result = CombatHealth.applyFixedDamage(state, 25, 0, "Test")
        expect(result.success).to.equal(true)
        expect(state.health).to.equal(initialHealth - 25)
      end)

      it("should return damage dealt in result", function()
        local state = CombatHealth.createState()
        local result = CombatHealth.applyFixedDamage(state, 30, 0, "Test")
        expect(result.damageDealt).to.equal(30)
        expect(result.newHealth).to.equal(state.health)
      end)

      it("should set inCombat state", function()
        local state = CombatHealth.createState()
        CombatHealth.applyFixedDamage(state, 10, 0, "Test")
        expect(state.inCombat).to.equal(true)
      end)

      it("should update lastDamageTime", function()
        local state = CombatHealth.createState()
        local currentTime = 5.5
        CombatHealth.applyFixedDamage(state, 10, currentTime, "Test")
        expect(state.lastDamageTime).to.equal(currentTime)
      end)
    end)

    describe("knockback", function()
      it("should occur when health depletes", function()
        local state = CombatHealth.createState()
        local result = CombatHealth.applyFixedDamage(state, 150, 0, "Test")
        expect(result.success).to.equal(true)
        expect(result.wasKnockedBack).to.equal(true)
      end)

      it("should set isKnockedBack state", function()
        local state = CombatHealth.createState()
        CombatHealth.applyFixedDamage(state, 150, 0, "Test")
        expect(state.isKnockedBack).to.equal(true)
      end)

      it("should set knockbackEndTime", function()
        local state = CombatHealth.createState()
        local currentTime = 0
        CombatHealth.applyFixedDamage(state, 150, currentTime, "Test")
        expect(state.knockbackEndTime > currentTime).to.equal(true)
      end)

      it("should prevent taking damage while knocked back", function()
        local state = CombatHealth.createState()
        CombatHealth.applyFixedDamage(state, 150, 0, "Test")
        local result = CombatHealth.applyFixedDamage(state, 25, 0.5, "Test")
        expect(result.success).to.equal(false)
      end)

      it("should return appropriate message when knocked back", function()
        local state = CombatHealth.createState()
        CombatHealth.applyFixedDamage(state, 150, 0, "Test")
        local result = CombatHealth.applyFixedDamage(state, 25, 0.5, "Test")
        expect(result.message).to.be.ok()
      end)
    end)

    describe("regeneration", function()
      it("should regenerate health when out of combat", function()
        local state = CombatHealth.createState()
        CombatHealth.applyFixedDamage(state, 30, 0, "Test")
        local constants = CombatHealth.getConstants()
        -- Wait for out of combat delay
        local currentTime = constants.outOfCombatDelay + 1
        local result = CombatHealth.regenerate(state, 1, currentTime)
        expect(result.healthRestored > 0).to.equal(true)
      end)

      it("should not regenerate when in combat", function()
        local state = CombatHealth.createState()
        CombatHealth.applyFixedDamage(state, 30, 0, "Test")
        -- Still within combat delay
        local result = CombatHealth.regenerate(state, 1, 1)
        expect(result.healthRestored).to.equal(0)
      end)

      it("should not regenerate when at full health", function()
        local state = CombatHealth.createState()
        local result = CombatHealth.regenerate(state, 1, 10)
        expect(result.healthRestored).to.equal(0)
        expect(result.isFullHealth).to.equal(true)
      end)

      it("should cap health at maxHealth", function()
        local state = CombatHealth.createState()
        CombatHealth.applyFixedDamage(state, 5, 0, "Test")
        local constants = CombatHealth.getConstants()
        local currentTime = constants.outOfCombatDelay + 1
        -- Regenerate for a long time
        CombatHealth.regenerate(state, 100, currentTime)
        expect(state.health).to.equal(state.maxHealth)
      end)
    end)

    describe("getDamage", function()
      it("should return correct values from PredatorConfig", function()
        local damage = PredatorConfig.getDamage("Bear")
        expect(damage > 0).to.equal(true)
      end)

      it("should return default for invalid predator type", function()
        local damage = PredatorConfig.getDamage("InvalidPredator")
        expect(damage).to.equal(5)
      end)
    end)

    describe("predator damage validation", function()
      it("should have valid damage values for all predators", function()
        local types = PredatorConfig.getAllTypes()
        for _, predType in ipairs(types) do
          local config = PredatorConfig.get(predType)
          expect(config).to.be.ok()
          expect(config.damage > 0).to.equal(true)
        end
      end)
    end)

    describe("incapacitate", function()
      it("should set incapacitated state", function()
        local state = CombatHealth.createState()
        local result = CombatHealth.incapacitate(state, "attacker123", 0)
        expect(result.success).to.equal(true)
        expect(state.isIncapacitated).to.equal(true)
        expect(result.duration > 0).to.equal(true)
      end)

      it("should set incapacitatedBy to attacker id", function()
        local state = CombatHealth.createState()
        CombatHealth.incapacitate(state, "attacker123", 0)
        expect(state.incapacitatedBy).to.equal("attacker123")
      end)

      it("should set incapacitatedEndTime", function()
        local state = CombatHealth.createState()
        local currentTime = 5
        CombatHealth.incapacitate(state, "attacker123", currentTime)
        expect(state.incapacitatedEndTime > currentTime).to.equal(true)
      end)

      it("should not incapacitate while already incapacitated", function()
        local state = CombatHealth.createState()
        CombatHealth.incapacitate(state, "attacker123", 0)
        local result = CombatHealth.incapacitate(state, "attacker456", 0.5)
        expect(result.success).to.equal(false)
      end)

      it("should not incapacitate while knocked back", function()
        local state = CombatHealth.createState()
        CombatHealth.applyFixedDamage(state, 150, 0, "Test")
        local result = CombatHealth.incapacitate(state, "attacker123", 0.5)
        expect(result.success).to.equal(false)
      end)
    end)

    describe("isIncapacitated", function()
      it("should return true when incapacitated", function()
        local state = CombatHealth.createState()
        CombatHealth.incapacitate(state, "attacker123", 0)
        local isIncap = CombatHealth.isIncapacitated(state, 0.5)
        expect(isIncap).to.equal(true)
      end)

      it("should expire after duration", function()
        local state = CombatHealth.createState()
        local result = CombatHealth.incapacitate(state, "attacker123", 0)
        local duration = result.duration
        local isIncapBefore = CombatHealth.isIncapacitated(state, 0.5)
        local isIncapAfter = CombatHealth.isIncapacitated(state, duration + 0.1)
        expect(isIncapBefore).to.equal(true)
        expect(isIncapAfter).to.equal(false)
      end)

      it("should clear incapacitatedBy when expired", function()
        local state = CombatHealth.createState()
        local result = CombatHealth.incapacitate(state, "attacker123", 0)
        -- Check after expiration
        CombatHealth.isIncapacitated(state, result.duration + 0.1)
        expect(state.incapacitatedBy).to.equal(nil)
      end)
    end)

    describe("canMove", function()
      it("should return true for fresh state", function()
        local state = CombatHealth.createState()
        local canMove = CombatHealth.canMove(state, 0)
        expect(canMove).to.equal(true)
      end)

      it("should return false when incapacitated", function()
        local state = CombatHealth.createState()
        CombatHealth.incapacitate(state, "attacker123", 0)
        local canMove = CombatHealth.canMove(state, 0.5)
        expect(canMove).to.equal(false)
      end)

      it("should return true when incapacitation expires", function()
        local state = CombatHealth.createState()
        local result = CombatHealth.incapacitate(state, "attacker123", 0)
        local canMove = CombatHealth.canMove(state, result.duration + 0.1)
        expect(canMove).to.equal(true)
      end)

      it("should return false when knocked back", function()
        local state = CombatHealth.createState()
        CombatHealth.applyFixedDamage(state, 150, 0, "Test")
        local canMove = CombatHealth.canMove(state, 0.5)
        expect(canMove).to.equal(false)
      end)
    end)

    describe("getIncapacitateConstants", function()
      it("should return valid values", function()
        local constants = CombatHealth.getIncapacitateConstants()
        expect(constants.duration > 0).to.equal(true)
        expect(constants.knockbackForce > 0).to.equal(true)
      end)

      it("should return consistent values", function()
        local constants1 = CombatHealth.getIncapacitateConstants()
        local constants2 = CombatHealth.getIncapacitateConstants()
        expect(constants1.duration).to.equal(constants2.duration)
        expect(constants1.knockbackForce).to.equal(constants2.knockbackForce)
      end)
    end)

    describe("getConstants", function()
      it("should return all required constants", function()
        local constants = CombatHealth.getConstants()
        expect(constants.maxHealth).to.be.ok()
        expect(constants.regenPerSecond).to.be.ok()
        expect(constants.outOfCombatDelay).to.be.ok()
        expect(constants.knockbackDuration).to.be.ok()
        expect(constants.combatRangeStuds).to.be.ok()
      end)

      it("should return positive values", function()
        local constants = CombatHealth.getConstants()
        expect(constants.maxHealth > 0).to.equal(true)
        expect(constants.regenPerSecond > 0).to.equal(true)
        expect(constants.outOfCombatDelay > 0).to.equal(true)
        expect(constants.knockbackDuration > 0).to.equal(true)
        expect(constants.combatRangeStuds > 0).to.equal(true)
      end)
    end)

    describe("utility functions", function()
      describe("getHealthPercent", function()
        it("should return 1 for full health", function()
          local state = CombatHealth.createState()
          expect(CombatHealth.getHealthPercent(state)).to.equal(1)
        end)

        it("should return correct percentage after damage", function()
          local state = CombatHealth.createState()
          CombatHealth.applyFixedDamage(state, 50, 0, "Test")
          expect(CombatHealth.getHealthPercent(state)).to.equal(0.5)
        end)
      end)

      describe("isFullHealth", function()
        it("should return true for full health", function()
          local state = CombatHealth.createState()
          expect(CombatHealth.isFullHealth(state)).to.equal(true)
        end)

        it("should return false after damage", function()
          local state = CombatHealth.createState()
          CombatHealth.applyFixedDamage(state, 10, 0, "Test")
          expect(CombatHealth.isFullHealth(state)).to.equal(false)
        end)
      end)

      describe("setHealth", function()
        it("should set health to specified value", function()
          local state = CombatHealth.createState()
          CombatHealth.setHealth(state, 50)
          expect(state.health).to.equal(50)
        end)

        it("should clamp health to max", function()
          local state = CombatHealth.createState()
          CombatHealth.setHealth(state, 200)
          expect(state.health).to.equal(state.maxHealth)
        end)

        it("should clamp health to zero", function()
          local state = CombatHealth.createState()
          CombatHealth.setHealth(state, -50)
          expect(state.health).to.equal(0)
        end)
      end)

      describe("reset", function()
        it("should restore full health", function()
          local state = CombatHealth.createState()
          CombatHealth.applyFixedDamage(state, 50, 0, "Test")
          CombatHealth.reset(state)
          expect(state.health).to.equal(state.maxHealth)
        end)

        it("should clear all combat states", function()
          local state = CombatHealth.createState()
          CombatHealth.applyFixedDamage(state, 150, 0, "Test")
          CombatHealth.incapacitate(state, "attacker", 10)
          CombatHealth.reset(state)
          expect(state.isKnockedBack).to.equal(false)
          expect(state.inCombat).to.equal(false)
          expect(state.isIncapacitated).to.equal(false)
          expect(state.incapacitatedBy).to.equal(nil)
        end)
      end)
    end)
  end)
end
