--[[
	PredatorAI.spec.lua
	TestEZ tests for PredatorAI module
]]

return function()
  local ReplicatedStorage = game:GetService("ReplicatedStorage")
  local Shared = ReplicatedStorage:WaitForChild("Shared")
  local PredatorAI = require(Shared:WaitForChild("PredatorAI"))

  describe("PredatorAI", function()
    describe("createState", function()
      it("should return valid state", function()
        local state = PredatorAI.createState()
        expect(state).to.be.ok()
        expect(state.positions).to.be.ok()
      end)
    end)

    describe("registerPredator", function()
      it("should add predator to state", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        local position = PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        expect(position).to.be.ok()
        expect(PredatorAI.getActiveCount(state)).to.equal(1)
      end)

      it("should spawn predator at section edge", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        local position = PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local distFromCenter = (position.spawnPosition - sectionCenter).Magnitude
        expect(distFromCenter > 30).to.equal(true)
      end)
    end)

    describe("updatePosition", function()
      it("should move predator towards target", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        local position = PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local initialDistance = (position.targetPosition - position.currentPosition).Magnitude
        PredatorAI.updatePosition(state, "pred1", 1)
        local newPosition = PredatorAI.getPosition(state, "pred1")
        local newDistance = (newPosition.targetPosition - newPosition.currentPosition).Magnitude
        expect(newDistance < initialDistance).to.equal(true)
      end)

      it("should allow predator to reach coop after enough time", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        for _ = 1, 20 do
          PredatorAI.updatePosition(state, "pred1", 1)
        end
        expect(PredatorAI.hasReachedCoop(state, "pred1")).to.equal(true)
      end)
    end)

    describe("unregisterPredator", function()
      it("should remove predator from state", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        PredatorAI.unregisterPredator(state, "pred1")
        expect(PredatorAI.getActiveCount(state)).to.equal(0)
      end)
    end)

    describe("getWalkSpeed", function()
      it("should make higher threat predators move faster", function()
        local ratSpeed = PredatorAI.getWalkSpeed("Rat")
        local bearSpeed = PredatorAI.getWalkSpeed("Bear")
        expect(bearSpeed > ratSpeed).to.equal(true)
      end)
    end)

    describe("getProgress", function()
      it("should return percentage starting at 0", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local initialProgress = PredatorAI.getProgress(state, "pred1")
        expect(initialProgress).to.equal(0)
      end)

      it("should increase progress after moving", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        PredatorAI.updatePosition(state, "pred1", 2)
        local afterProgress = PredatorAI.getProgress(state, "pred1")
        expect(afterProgress > 0).to.equal(true)
      end)
    end)

    describe("getTimeToReachCoop", function()
      it("should return positive estimate", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local timeEstimate = PredatorAI.getTimeToReachCoop(state, "pred1")
        expect(timeEstimate > 0).to.equal(true)
      end)
    end)

    describe("getApproachingPredators", function()
      it("should return correct list", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        PredatorAI.registerPredator(state, "pred2", "Crow", sectionCenter)
        local approaching = PredatorAI.getApproachingPredators(state)
        expect(#approaching).to.equal(2)
      end)
    end)

    describe("registerRoamingPredator", function()
      it("should create roaming predator", function()
        local state = PredatorAI.createState(Vector3.new(0, 0, 0), 80)
        local currentTime = os.time()
        local position = PredatorAI.registerRoamingPredator(state, "roamer1", "Rat", currentTime)
        expect(position).to.be.ok()
        expect(position.behaviorState).to.equal("roaming")
        expect(position.roamTarget).to.be.ok()
      end)

      it("should keep roaming predator in neutral zone", function()
        local center = Vector3.new(50, 0, 50)
        local size = 40
        local state = PredatorAI.createState(center, size)
        local currentTime = os.time()
        local position = PredatorAI.registerRoamingPredator(state, "roamer1", "Rat", currentTime)
        local halfSize = size / 2
        local inBounds = position.currentPosition.X >= center.X - halfSize
          and position.currentPosition.X <= center.X + halfSize
          and position.currentPosition.Z >= center.Z - halfSize
          and position.currentPosition.Z <= center.Z + halfSize
        expect(inBounds).to.equal(true)
      end)
    end)

    describe("updateRoaming", function()
      it("should move roaming predator", function()
        local state = PredatorAI.createState(Vector3.new(0, 0, 0), 80)
        local currentTime = os.time()
        PredatorAI.registerRoamingPredator(state, "roamer1", "Rat", currentTime)
        local initialPos = PredatorAI.getPosition(state, "roamer1")
        local initialX = initialPos.currentPosition.X
        local initialZ = initialPos.currentPosition.Z
        PredatorAI.updateRoaming(state, "roamer1", 2, currentTime + 2)
        local newPos = PredatorAI.getPosition(state, "roamer1")
        local moved = newPos.currentPosition.X ~= initialX or newPos.currentPosition.Z ~= initialZ
        expect(moved).to.equal(true)
      end)
    end)

    describe("shouldSeekTarget", function()
      it("should return false immediately after spawn", function()
        local state = PredatorAI.createState(Vector3.new(0, 0, 0), 80)
        local startTime = os.time()
        PredatorAI.registerRoamingPredator(state, "roamer1", "Rat", startTime)
        expect(PredatorAI.shouldSeekTarget(state, "roamer1", startTime + 1)).to.equal(false)
      end)

      it("should return true after roam time expires", function()
        local state = PredatorAI.createState(Vector3.new(0, 0, 0), 80)
        local startTime = os.time()
        local position = PredatorAI.registerRoamingPredator(state, "roamer1", "Rat", startTime)
        local afterRoamTime = (position.roamEndTime or startTime) + 1
        expect(PredatorAI.shouldSeekTarget(state, "roamer1", afterRoamTime)).to.equal(true)
      end)
    end)

    describe("startStalking", function()
      it("should transition to stalking state", function()
        local state = PredatorAI.createState(Vector3.new(0, 0, 0), 80)
        local currentTime = os.time()
        PredatorAI.registerRoamingPredator(state, "roamer1", "Rat", currentTime)
        local targetSection = {
          sectionIndex = 1,
          center = Vector3.new(100, 0, 0),
          chickenCount = 5,
          distance = 30,
        }
        PredatorAI.startStalking(state, "roamer1", targetSection, currentTime)
        local position = PredatorAI.getPosition(state, "roamer1")
        expect(position.behaviorState).to.equal("stalking")
        expect(position.isStalking).to.equal(true)
      end)
    end)

    describe("startApproaching", function()
      it("should transition from stalking to approaching", function()
        local state = PredatorAI.createState(Vector3.new(0, 0, 0), 80)
        local currentTime = os.time()
        PredatorAI.registerRoamingPredator(state, "roamer1", "Rat", currentTime)
        local targetSection = {
          sectionIndex = 1,
          center = Vector3.new(100, 0, 0),
          chickenCount = 5,
          distance = 30,
        }
        PredatorAI.startStalking(state, "roamer1", targetSection, currentTime)
        PredatorAI.startApproaching(state, "roamer1", Vector3.new(100, 0, 0))
        local position = PredatorAI.getPosition(state, "roamer1")
        expect(position.behaviorState).to.equal("approaching")
        expect(position.isStalking).to.equal(false)
      end)
    end)

    describe("getRoamingPredators", function()
      it("should return only roaming predators", function()
        local state = PredatorAI.createState(Vector3.new(0, 0, 0), 80)
        local currentTime = os.time()
        PredatorAI.registerRoamingPredator(state, "roamer1", "Rat", currentTime)
        PredatorAI.registerPredator(state, "direct1", "Crow", Vector3.new(50, 0, 50))
        local roaming = PredatorAI.getRoamingPredators(state)
        expect(#roaming).to.equal(1)
        expect(roaming[1]).to.equal("roamer1")
      end)
    end)

    describe("getSummary", function()
      it("should include roaming and stalking counts", function()
        local state = PredatorAI.createState(Vector3.new(0, 0, 0), 80)
        local currentTime = os.time()
        PredatorAI.registerRoamingPredator(state, "roamer1", "Rat", currentTime)
        PredatorAI.registerPredator(state, "direct1", "Crow", Vector3.new(50, 0, 50))
        local summary = PredatorAI.getSummary(state)
        expect(summary.roaming).to.equal(1)
        expect(summary.approaching).to.equal(1)
        expect(summary.totalActive).to.equal(2)
      end)

      it("should include fleeing and cautious counts", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        PredatorAI.registerPredator(state, "pred2", "Crow", sectionCenter)
        local currentTime = os.time()
        PredatorAI.startFleeing(state, "pred1", currentTime, sectionCenter)
        local position = PredatorAI.getPosition(state, "pred2")
        local playerPos = position.currentPosition + Vector3.new(10, 0, 0)
        PredatorAI.updatePlayerAwareness(state, "pred2", playerPos, true, currentTime)
        local summary = PredatorAI.getSummary(state)
        expect(summary.fleeing).to.equal(1)
        expect(summary.cautious).to.equal(1)
      end)
    end)

    describe("patrol behavior", function()
      it("should activate when attacking", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        for _ = 1, 100 do
          PredatorAI.updatePosition(state, "pred1", 1, os.clock())
        end
        local position = PredatorAI.getPosition(state, "pred1")
        expect(position.behaviorState).to.equal("attacking")
        PredatorAI.updatePosition(state, "pred1", 0.1, os.clock())
        position = PredatorAI.getPosition(state, "pred1")
        expect(position.coopCenter).to.be.ok()
      end)
    end)

    describe("updateChickenPresence", function()
      it("should track no chickens time", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        for _ = 1, 100 do
          PredatorAI.updatePosition(state, "pred1", 1, os.clock())
        end
        local currentTime = os.time()
        local shouldDespawn = PredatorAI.updateChickenPresence(state, "pred1", false, currentTime)
        expect(shouldDespawn).to.equal(false)
        local position = PredatorAI.getPosition(state, "pred1")
        expect(position.noChickensTime).to.be.ok()
      end)

      it("should prevent despawn when engaging player", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        for _ = 1, 100 do
          PredatorAI.updatePosition(state, "pred1", 1, os.clock())
        end
        local startTime = os.time()
        PredatorAI.updateChickenPresence(state, "pred1", false, startTime, false)
        local position = PredatorAI.getPosition(state, "pred1")
        expect(position.noChickensTime).to.be.ok()
        PredatorAI.updateChickenPresence(state, "pred1", false, startTime + 5, true)
        position = PredatorAI.getPosition(state, "pred1")
        expect(position.noChickensTime).to.equal(nil)
        local shouldDespawn =
          PredatorAI.updateChickenPresence(state, "pred1", false, startTime + 15, true)
        expect(shouldDespawn).to.equal(false)
      end)
    end)

    describe("shouldDespawn", function()
      it("should return true after enough time without chickens", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        for _ = 1, 100 do
          PredatorAI.updatePosition(state, "pred1", 1, os.clock())
        end
        local startTime = os.time()
        PredatorAI.updateChickenPresence(state, "pred1", false, startTime)
        local shouldDespawn = PredatorAI.shouldDespawn(state, "pred1", startTime)
        expect(shouldDespawn).to.equal(false)
        shouldDespawn = PredatorAI.shouldDespawn(state, "pred1", startTime + 10)
        expect(shouldDespawn).to.equal(true)
      end)
    end)

    describe("setTargetChicken", function()
      it("should store target spot", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local spotPos = Vector3.new(5, 1, 5)
        local success = PredatorAI.setTargetChicken(state, "pred1", 3, spotPos)
        expect(success).to.equal(true)
        local targetSpot = PredatorAI.getTargetChicken(state, "pred1")
        expect(targetSpot).to.equal(3)
      end)
    end)

    describe("shouldFlee", function()
      it("should return true when health below threshold", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local shouldFlee = PredatorAI.shouldFlee(state, "pred1", 3, 10)
        expect(shouldFlee).to.equal(true)
      end)

      it("should return false when health above threshold", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local shouldFlee = PredatorAI.shouldFlee(state, "pred1", 5, 10)
        expect(shouldFlee).to.equal(false)
      end)
    end)

    describe("startFleeing", function()
      it("should transition to fleeing state", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local currentTime = os.time()
        local damageSource = Vector3.new(10, 0, 10)
        local success = PredatorAI.startFleeing(state, "pred1", currentTime, damageSource)
        expect(success).to.equal(true)
        expect(PredatorAI.isFleeing(state, "pred1")).to.equal(true)
      end)
    end)

    describe("updateFleeing", function()
      it("should move predator away", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local currentTime = os.time()
        local damageSource = Vector3.new(10, 0, 10)
        PredatorAI.startFleeing(state, "pred1", currentTime, damageSource)
        local initialPos = PredatorAI.getPosition(state, "pred1").currentPosition
        PredatorAI.updateFleeing(state, "pred1", 1, currentTime + 1)
        local newPos = PredatorAI.getPosition(state, "pred1").currentPosition
        local moved = (newPos - initialPos).Magnitude > 0
        expect(moved).to.equal(true)
      end)
    end)

    describe("updatePlayerAwareness", function()
      it("should detect nearby player", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local position = PredatorAI.getPosition(state, "pred1")
        local playerPos = position.currentPosition + Vector3.new(10, 0, 0)
        local currentTime = os.time()
        local result =
          PredatorAI.updatePlayerAwareness(state, "pred1", playerPos, false, currentTime)
        expect(result.detected).to.equal(true)
      end)

      it("should become cautious when player has weapon", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local position = PredatorAI.getPosition(state, "pred1")
        local playerPos = position.currentPosition + Vector3.new(10, 0, 0)
        local currentTime = os.time()
        local result =
          PredatorAI.updatePlayerAwareness(state, "pred1", playerPos, true, currentTime)
        expect(result.becameCautious).to.equal(true)
        expect(PredatorAI.isCautious(state, "pred1")).to.equal(true)
      end)
    end)

    describe("onDamage", function()
      it("should trigger fleeing when health low", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local currentTime = os.time()
        local damageSource = Vector3.new(5, 0, 5)
        local result = PredatorAI.onDamage(state, "pred1", 2, 10, damageSource, currentTime)
        expect(result.startedFleeing).to.equal(true)
        expect(PredatorAI.isFleeing(state, "pred1")).to.equal(true)
      end)
    end)

    describe("updateShieldAwareness", function()
      it("should cause retreat when shield active", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local currentTime = os.time()
        local result =
          PredatorAI.updateShieldAwareness(state, "pred1", true, sectionCenter, currentTime)
        expect(result.retreating).to.equal(true)
      end)
    end)

    describe("getAggressionLevel", function()
      it("should return correct values for different threat levels", function()
        local ratAggression = PredatorAI.getAggressionLevel("Rat")
        local bearAggression = PredatorAI.getAggressionLevel("Bear")
        expect(ratAggression).to.equal(1)
        expect(bearAggression).to.equal(6)
      end)
    end)

    describe("hasEnteredSection", function()
      it("should return true when predator is inside section", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        for _ = 1, 15 do
          PredatorAI.updatePosition(state, "pred1", 1, os.clock())
        end
        local inSection = PredatorAI.hasEnteredSection(state, "pred1")
        expect(inSection).to.equal(true)
      end)

      it("should return false when predator is outside section", function()
        local state = PredatorAI.createState()
        local sectionCenter = Vector3.new(0, 0, 0)
        PredatorAI.registerPredator(state, "pred1", "Rat", sectionCenter)
        local inSection = PredatorAI.hasEnteredSection(state, "pred1")
        expect(inSection).to.equal(false)
      end)
    end)
  end)
end
