--[[
	LevelService Tests
	Tests for the LevelService Knit service.
]]

return function()
  local ReplicatedStorage = game:GetService("ReplicatedStorage")

  local Shared = ReplicatedStorage:WaitForChild("Shared")
  local LevelConfig = require(Shared:WaitForChild("LevelConfig"))
  local XPConfig = require(Shared:WaitForChild("XPConfig"))

  describe("LevelConfig", function()
    describe("getXPForLevel", function()
      it("should return 0 for level 1", function()
        expect(LevelConfig.getXPForLevel(1)).to.equal(0)
      end)

      it("should return base XP for level 2", function()
        expect(LevelConfig.getXPForLevel(2)).to.equal(100)
      end)

      it("should increase XP requirements with level", function()
        local level2XP = LevelConfig.getXPForLevel(2)
        local level3XP = LevelConfig.getXPForLevel(3)
        local level4XP = LevelConfig.getXPForLevel(4)

        expect(level3XP).to.be.greaterThan(level2XP)
        expect(level4XP).to.be.greaterThan(level3XP)
      end)

      it("should handle max level", function()
        local maxXP = LevelConfig.getXPForLevel(100)
        expect(maxXP).to.be.greaterThan(0)
      end)
    end)

    describe("getLevelFromXP", function()
      it("should return level 1 for 0 XP", function()
        expect(LevelConfig.getLevelFromXP(0)).to.equal(1)
      end)

      it("should return level 1 for XP below threshold", function()
        expect(LevelConfig.getLevelFromXP(50)).to.equal(1)
      end)

      it("should return level 2 at 100 XP", function()
        expect(LevelConfig.getLevelFromXP(100)).to.equal(2)
      end)

      it("should return correct level for high XP", function()
        local level = LevelConfig.getLevelFromXP(10000)
        expect(level).to.be.greaterThan(10)
      end)
    end)

    describe("getLevelProgress", function()
      it("should return 0 at start of level", function()
        local progress = LevelConfig.getLevelProgress(0)
        expect(progress).to.be.near(0, 0.01)
      end)

      it("should return 1 at max level", function()
        local maxXP = LevelConfig.getXPForLevel(100)
        local progress = LevelConfig.getLevelProgress(maxXP)
        expect(progress).to.equal(1)
      end)

      it("should return value between 0 and 1", function()
        local progress = LevelConfig.getLevelProgress(150)
        expect(progress).to.be.greaterThanOrEqualTo(0)
        expect(progress).to.be.lessThanOrEqualTo(1)
      end)
    end)

    describe("getXPToNextLevel", function()
      it("should return XP needed for level 2 at 0 XP", function()
        local xpNeeded = LevelConfig.getXPToNextLevel(0)
        expect(xpNeeded).to.equal(100)
      end)

      it("should return nil at max level", function()
        local maxXP = LevelConfig.getXPForLevel(100)
        local xpNeeded = LevelConfig.getXPToNextLevel(maxXP)
        expect(xpNeeded).to.equal(nil)
      end)

      it("should decrease as XP increases within level", function()
        local xpNeeded50 = LevelConfig.getXPToNextLevel(50)
        local xpNeeded75 = LevelConfig.getXPToNextLevel(75)
        expect(xpNeeded75).to.be.lessThan(xpNeeded50)
      end)
    end)

    describe("getMaxPredatorsForLevel", function()
      it("should return 1 for level 1", function()
        expect(LevelConfig.getMaxPredatorsForLevel(1)).to.equal(1)
      end)

      it("should increase every 5 levels", function()
        expect(LevelConfig.getMaxPredatorsForLevel(5)).to.equal(1)
        expect(LevelConfig.getMaxPredatorsForLevel(6)).to.equal(2)
        expect(LevelConfig.getMaxPredatorsForLevel(10)).to.equal(2)
        expect(LevelConfig.getMaxPredatorsForLevel(11)).to.equal(3)
      end)

      it("should cap at 8 predators", function()
        expect(LevelConfig.getMaxPredatorsForLevel(100)).to.equal(8)
      end)
    end)

    describe("getThreatMultiplierForLevel", function()
      it("should return 1.0 at level 1", function()
        expect(LevelConfig.getThreatMultiplierForLevel(1)).to.equal(1.0)
      end)

      it("should return 2.0 at max level", function()
        expect(LevelConfig.getThreatMultiplierForLevel(100)).to.equal(2.0)
      end)

      it("should scale linearly between 1.0 and 2.0", function()
        local mult50 = LevelConfig.getThreatMultiplierForLevel(50)
        expect(mult50).to.be.greaterThan(1.0)
        expect(mult50).to.be.lessThan(2.0)
      end)
    end)

    describe("isThreatLevelUnlocked", function()
      it("should unlock Minor at level 1", function()
        expect(LevelConfig.isThreatLevelUnlocked(1, "Minor")).to.equal(true)
      end)

      it("should not unlock Moderate at level 1", function()
        expect(LevelConfig.isThreatLevelUnlocked(1, "Moderate")).to.equal(false)
      end)

      it("should unlock Moderate at level 5", function()
        expect(LevelConfig.isThreatLevelUnlocked(5, "Moderate")).to.equal(true)
      end)

      it("should unlock Dangerous at level 15", function()
        expect(LevelConfig.isThreatLevelUnlocked(15, "Dangerous")).to.equal(true)
      end)

      it("should unlock all at level 100", function()
        expect(LevelConfig.isThreatLevelUnlocked(100, "Minor")).to.equal(true)
        expect(LevelConfig.isThreatLevelUnlocked(100, "Moderate")).to.equal(true)
        expect(LevelConfig.isThreatLevelUnlocked(100, "Dangerous")).to.equal(true)
        expect(LevelConfig.isThreatLevelUnlocked(100, "Severe")).to.equal(true)
        expect(LevelConfig.isThreatLevelUnlocked(100, "Deadly")).to.equal(true)
        expect(LevelConfig.isThreatLevelUnlocked(100, "Catastrophic")).to.equal(true)
      end)
    end)

    describe("getMaxThreatLevel", function()
      it("should return Minor at level 1", function()
        expect(LevelConfig.getMaxThreatLevel(1)).to.equal("Minor")
      end)

      it("should return Moderate at level 5", function()
        expect(LevelConfig.getMaxThreatLevel(5)).to.equal("Moderate")
      end)
    end)

    describe("getLevelData", function()
      it("should return valid level data", function()
        local data = LevelConfig.getLevelData(1)
        expect(data.level).to.equal(1)
        expect(data.xpRequired).to.equal(0)
        expect(data.maxSimultaneousPredators).to.equal(1)
        expect(data.predatorThreatMultiplier).to.equal(1.0)
      end)

      it("should include xpToNextLevel for non-max levels", function()
        local data = LevelConfig.getLevelData(5)
        expect(data.xpToNextLevel).to.be.ok()
        expect(data.xpToNextLevel).to.be.greaterThan(0)
      end)

      it("should have nil xpToNextLevel at max level", function()
        local data = LevelConfig.getLevelData(100)
        expect(data.xpToNextLevel).to.equal(nil)
      end)
    end)

    describe("getLevelUpBonusXP", function()
      it("should return 0 for non-milestone levels", function()
        expect(LevelConfig.getLevelUpBonusXP(3)).to.equal(0)
        expect(LevelConfig.getLevelUpBonusXP(7)).to.equal(0)
      end)

      it("should return 200 for level 5 milestones", function()
        expect(LevelConfig.getLevelUpBonusXP(5)).to.equal(200)
        expect(LevelConfig.getLevelUpBonusXP(15)).to.equal(200)
      end)

      it("should return 500 for level 10 milestones", function()
        expect(LevelConfig.getLevelUpBonusXP(10)).to.equal(500)
        expect(LevelConfig.getLevelUpBonusXP(50)).to.equal(500)
      end)
    end)

    describe("validation", function()
      it("should validate level values", function()
        expect(LevelConfig.isValidLevel(1)).to.equal(true)
        expect(LevelConfig.isValidLevel(50)).to.equal(true)
        expect(LevelConfig.isValidLevel(100)).to.equal(true)
        expect(LevelConfig.isValidLevel(0)).to.equal(false)
        expect(LevelConfig.isValidLevel(101)).to.equal(false)
        expect(LevelConfig.isValidLevel(5.5)).to.equal(false)
      end)

      it("should validate XP values", function()
        expect(LevelConfig.isValidXP(0)).to.equal(true)
        expect(LevelConfig.isValidXP(1000)).to.equal(true)
        expect(LevelConfig.isValidXP(-1)).to.equal(false)
        expect(LevelConfig.isValidXP(5.5)).to.equal(false)
      end)
    end)
  end)

  describe("XPConfig", function()
    describe("getBaseReward", function()
      it("should return base XP for predator_killed", function()
        local xp = XPConfig.getBaseReward("predator_killed")
        expect(xp).to.equal(25)
      end)

      it("should return base XP for chicken_hatched", function()
        local xp = XPConfig.getBaseReward("chicken_hatched")
        expect(xp).to.equal(10)
      end)

      it("should return 0 for unknown type", function()
        local xp = XPConfig.getBaseReward("unknown_type")
        expect(xp).to.equal(0)
      end)
    end)

    describe("calculatePredatorKillXP", function()
      it("should return base XP for unknown predator", function()
        local xp = XPConfig.calculatePredatorKillXP("UnknownPredator")
        expect(xp).to.equal(25)
      end)
    end)

    describe("calculateChickenHatchXP", function()
      it("should scale with rarity", function()
        local commonXP = XPConfig.calculateChickenHatchXP("Common")
        local rareXP = XPConfig.calculateChickenHatchXP("Rare")
        local legendaryXP = XPConfig.calculateChickenHatchXP("Legendary")

        expect(rareXP).to.be.greaterThan(commonXP)
        expect(legendaryXP).to.be.greaterThan(rareXP)
      end)

      it("should return base XP for unknown rarity", function()
        local xp = XPConfig.calculateChickenHatchXP("Unknown")
        expect(xp).to.equal(10)
      end)
    end)

    describe("calculateDayNightCycleXP", function()
      it("should return flat XP amount", function()
        local xp = XPConfig.calculateDayNightCycleXP()
        expect(xp).to.equal(15)
      end)
    end)

    describe("getRarityMultiplier", function()
      it("should return correct multipliers", function()
        expect(XPConfig.getRarityMultiplier("Common")).to.equal(1)
        expect(XPConfig.getRarityMultiplier("Uncommon")).to.equal(2)
        expect(XPConfig.getRarityMultiplier("Rare")).to.equal(4)
        expect(XPConfig.getRarityMultiplier("Epic")).to.equal(8)
        expect(XPConfig.getRarityMultiplier("Legendary")).to.equal(16)
        expect(XPConfig.getRarityMultiplier("Mythic")).to.equal(32)
      end)

      it("should return 1 for unknown rarity", function()
        expect(XPConfig.getRarityMultiplier("Unknown")).to.equal(1)
      end)
    end)

    describe("getThreatMultiplier", function()
      it("should return correct multipliers", function()
        expect(XPConfig.getThreatMultiplier("Minor")).to.equal(1)
        expect(XPConfig.getThreatMultiplier("Moderate")).to.equal(2)
        expect(XPConfig.getThreatMultiplier("Dangerous")).to.equal(4)
        expect(XPConfig.getThreatMultiplier("Severe")).to.equal(8)
        expect(XPConfig.getThreatMultiplier("Deadly")).to.equal(16)
        expect(XPConfig.getThreatMultiplier("Catastrophic")).to.equal(32)
      end)

      it("should return 1 for unknown threat", function()
        expect(XPConfig.getThreatMultiplier("Unknown")).to.equal(1)
      end)
    end)

    describe("getAllRewardTypes", function()
      it("should return all reward types", function()
        local types = XPConfig.getAllRewardTypes()
        expect(#types).to.equal(6)
        expect(table.find(types, "predator_killed")).to.be.ok()
        expect(table.find(types, "chicken_hatched")).to.be.ok()
        expect(table.find(types, "day_night_cycle_survived")).to.be.ok()
      end)
    end)
  end)
end
